spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: "admin"
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1.0
